### ISSUE TITLE
Issue in Production build

### ISSUE THREAD

**Issue by nitiandiv** [xiaolin/react-image-gallery#624] opened 2021-08-12 10:59 UTC
**Describe the bug**
Issue in Production build

**To Reproduce**
created bundle and deploy

**Expected behavior**
it should open shown w/o any error

**Desktop (please complete the following information):**
issue started coming in 1-2 days

react_devtools_backend.js:2574 TypeError: Super expression must either be null or a function
    at image-gallery.js:1094
    at image-gallery.js:1093
    at image-gallery.js:1092
    at image-gallery.js:375
    at Object.<anonymous> (image-gallery.js:4)
    at Object.1311 (image-gallery.js:4)
    at b (jobList?challenge_id=6114cddd5c90a30008b69f09:14)
    at Module.1338 (videoPart.js:114)
    at b (jobList?challenge_id=6114cddd5c90a30008b69f09:14)
overrideMethod @ react_devtools_backend.js:2574
is @ react-dom.production.min.js:5058
r.callback @ react-dom.production.min.js:5568
da @ react-dom.production.min.js:3108
us @ react-dom.production.min.js:5182
(anonymous) @ react-dom.production.min.js:6408
t.unstable_runWithPriority @ scheduler.production.min.js:309
jn @ react-dom.production.min.js:2816
Nu @ react-dom.production.min.js:6204
cu @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
t.unstable_runWithPriority @ scheduler.production.min.js:309
jn @ react-dom.production.min.js:2816
Qn @ react-dom.production.min.js:2846
U @ scheduler.production.min.js:203
T.port1.onmessage @ scheduler.production.min.js:94

**Additional context**

**Comment by xiaolin** [comment] 2021-08-12 21:09
This looks like a duplicate of #621. Can you explain a little more, the stack trace doesn't help much here. Are you able to get the library working in a development build?

**Comment by xiaolin** [comment] 2021-08-12 21:13
For what it's worth, the demo site is using a latest production build of `react-image-gallery`.

https://www.linxtion.com/demo/react-image-gallery/

**Comment by ThatSkiPatroller** [comment] 2021-09-09 09:53
I am currently having this same issue. The image gallery runs perfect locally, but when I try to deploy it I get the 'TypeError: Super expression must either be null or a function' error and I can only see the background color of the page, no components.

**Comment by jobindcruz** [comment] 2021-09-09 10:25
I got same error in production build

**Comment by xiaolin** [comment] 2021-09-09 17:22
Is there any issues with your imports? See 
https://stackoverflow.com/questions/30116430/reactjs-giving-error-uncaught-typeerror-super-expression-must-either-be-null-or

**Comment by Anilkumar18** [comment] 2021-09-24 05:06
Face the same issue on a production build. Is there any solution found?
I tried all the possibilities from the above link. Nothing can make work on it.
Thanks in advance

**Comment by jyelewis** [comment] 2021-12-06 19:01
I'm seeing this same issue, seems to only occur when webpack minimize is enabled.

In webpack.config.js
```
optimization: {
  minimize: true,
}
```

**Comment by jeferbc** [comment] 2021-12-23 17:38
Any solution? I have the same issue

**Comment by T0to22** [comment] 2022-03-17 17:28
Any help or solution? Same issue here

**Comment by TomlDev** [comment] 2022-04-26 10:20
Same issue here

**Comment by hu-milize** [comment] 2022-05-22 02:38
Same issue here

**Comment by BuckeyeCoder** [comment] 2022-06-21 08:19
Same issue. Using create-react-app straight up, no ejected code. Looks like this project is abandoned.

**Comment by xiaolin** [comment] 2022-06-21 17:15
There is a "can't replicate" label on this issue, if anyone can provide clear steps to reproduce It will help debug and solve this issue.

**Comment by Muhzn** [comment] 2022-06-22 09:01
I see the issue in Ubuntu 20. My issue has fixed when I downgraded the ubuntu version (My project was dockerized).

**Comment by gimurpe** [comment] 2022-06-30 15:01
@xiaolin I think you can try with node 14.8.0 and   webpack minimize enabled.

In webpack.config.js

```
optimization: {
  minimize: true,
}
```

**Comment by gimurpe** [comment] 2022-06-30 15:06
@xiaolin I can confirm that after disabling webpack minimize the issue stoped occurring

**Comment by gimurpe** [comment] 2022-06-30 15:59
If you don't want to disable the minimize property you can make this work with the following code:

Useful links:
[terser-webpack-plugin](https://webpack.js.org/plugins/terser-webpack-plugin/#exclude)
[webpack optimization minimize](https://webpack.js.org/configuration/optimization/#optimizationminimize)

npm install terser-webpack-plugin --save-dev for webpack v5
npm install terser-webpack-plugin@4.2.3 --save-dev for webpack v4

webpack.config.js

`const TerserPlugin = require('terser-webpack-plugin');`

```
  optimization = {
    minimize: true,
    minimizer: [new TerserPlugin({ exclude: /\/node_modules\/react-image-gallery/ })],
  };
```
or

config-overrides.js

`const TerserPlugin = require('terser-webpack-plugin');`

`  config.optimization = {
    minimize: true,
    minimizer: [new TerserPlugin({ exclude: /\/node_modules\/react-image-gallery/ })],
  };
`

**Comment by superCoderDOM** [comment] 2022-07-13 14:16
Same issue.

**Comment by PriyaJainDev** [comment] 2022-08-05 18:23
Same issue. Seeing the comments above to add ```
optimization: {
  minimize: true,
}
```
how to add this object with the new React v18?

**Comment by iamarturr** [comment] 2022-09-27 19:18
Same issue...

**Comment by Murtala-1** [comment] 2022-10-09 21:06
Same here

**Comment by xiaolin** [comment] 2022-10-10 00:16
Closing this as steps to reproduce is not clear and there are many instances of this lib in production. If you're able to reproduce with this package isolated please list steps and repopen.

**Closed by xiaolin** 2022-10-10 00:16 UTC
Labels: cant-replicate

**Comment by greenais** [comment] 2022-11-23 05:56
In case someone will bump here in search for any solution but "disable minimizing at all" - I can confirm that @gimurpe 's one works like charm (tested for Webpack 4).
Thank you a lot, camarade!

**Comment by 00simba** [comment] 2022-12-04 04:53
Adding this to my config-overrides.js fixed it for me, thanks to @gimurpe (Webpack 4 and npm install terser-webpack-plugin@4.2.3 --save-dev)

```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = function override(webpackConfig) {
    webpackConfig.optimization = (
      {
        minimize: true,
        minimizer: [new TerserPlugin({ exclude: /\/node_modules\/react-image-gallery/ })],
      }
    )
    return webpackConfig;
  }
```

**Comment by xiaolin** [comment] 2022-12-04 06:41
FWIW, I tried to reproduce using the config below and was not able to replicate the issue.

package.json
``` 
"react-image-gallery": "^1.1.1",
"terser-webpack-plugin": "^5.3.6",
"webpack": "^5.30.0",
```
webpack.config.js
```
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()],
  },
```

**Comment by 00simba** [comment] 2022-12-04 06:46
here is what fixed it for me, thank you @gimurpe 

added the following to my config-overrides.js

```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = function override(webpackConfig) {
    webpackConfig.optimization = 
      {
        minimize: true,
        minimizer: [new TerserPlugin({ exclude: /\/node_modules\/react-image-gallery/ })],
      }
    return webpackConfig;
  }
```

```    
"terser-webpack-plugin": "^4.2.3",
"webpack": "^4.28.3"
```

**Comment by iget-master** [comment] 2023-09-22 17:05
I confirm that minification causes this, but it's a random issue. I'm working for a year on a project and now after a rebuild it just throw this error.
