### ISSUE TITLE
renderItem is not pure

### ISSUE THREAD

**Issue by trixn86** [xiaolin/react-image-gallery#448] opened 2019-10-25 09:51 UTC
I was trying to inject extra props to the `<img />` element rendered by the library. Unfortunately `renderItem` is not pure because it uses `this.props.onImageError`, `this.props.onImageLoad` and `this.handleImageError` which makes it impossible to preserve the default error handling behaviour when overriding `renderItem` without extending the whole class. But this would be against the philosophy of react. The `renderItem` function should be pure meaning that it should be passed everything it needs to render as arguments not accessing any of its instance properties so that you can easily provide a custom render function that preserves the default functionality.

Would you accept a PR to change that?

**Comment by xiaolin** [comment] 2019-10-26 04:04
see #423 I'm pretty sure it is related. If so feel free to open a PR.

**Comment by xiaolin** [comment] 2019-10-29 19:13
Duplicate of #423.

**Closed by xiaolin** 2019-10-29 19:13 UTC
Labels: enhancement

**Comment by xiaolin** [comment] 2020-01-13 04:09
This specific issue with onImageLoad and onImageError should be  fixed in a separate commit.
