### ISSUE TITLE
Wait for image to load on navigate next

### ISSUE THREAD

**Issue by ErikParso** [xiaolin/react-image-gallery#530] opened 2020-07-07 13:25 UTC
When using navigation (with lazy loading and slow connection), I am able to navigate to not loaded image. Image loads in the middle of animation. Is it possible to delay navigation while neighbour image is loading ?

**Comment by xiaolin** [comment] 2020-07-11 00:25
You can possibly disable the navigation until the image is loaded but that may not be the best solution. Ideally a loading indicator shows up while the image loads. 

Marking this as duplicate of #427.

**Closed by xiaolin** 2020-07-11 00:25 UTC

**Comment by ErikParso** [comment] 2020-07-15 14:02
Images in gallery has different ratio. With loading indicator or dummy image is scrolling through gallery jumpy (my gallery has fixed height, and dynamic width). First required method (nav buttons dissabling) seems to be good solutin for me :)
