### ISSUE TITLE
The border will not disappear in mobile if you click thumbnail image and then slide the image.

### ISSUE THREAD

**Issue by xiaogliu** [xiaolin/react-image-gallery#507] opened 2020-04-26 12:15 UTC
Version: 1.0.7
Description: The border will not disappear in mobile if you click thumbnail image and then slide the image.
Reproduce: use chrome to access this url https://www.linxtion.com/demo/react-image-gallery/ and change it to mobile version, click thumbnail image and then slide image.

**Comment by xiaolin** [comment] 2020-05-08 01:43
I can't reproduce this. Can you show me a screenshot?

**Comment by xiaolin** [comment] 2020-05-08 01:57
I can't reproduce this. Can you show me a screenshot?

**Comment by xiaogliu** [comment] 2020-05-10 07:32
![image](https://user-images.githubusercontent.com/15944323/81493520-7d875f80-92d3-11ea-9faa-7bbd2efc5e8e.png)

**Comment by AustinLeeGordon** [comment] 2020-06-17 13:49
Here's the css that's causing it.

https://github.com/xiaolin/react-image-gallery/blob/a3cdfeeff31fa8d3b3bc8844a64758fc4d836eee/styles/scss/image-gallery.scss#L375-L384

If you click the thumbnail and use the keyboard to change slides, you're still focusing on the other thumbnail. Would it help to have a different style for focus/hover vs active? I don't think you would want to change the focus in any way.

**Comment by xiaolin** [comment] 2021-05-28 08:57
Released in v1.0.10 https://github.com/xiaolin/react-image-gallery/releases/tag/v1.0.10

**Closed by xiaolin** 2021-05-28 08:57 UTC
Labels: need-investigation, needs-release
