### ISSUE TITLE
Multiple gallery and arrow keys

### ISSUE THREAD

**Issue by tsotneguti** [xiaolin/react-image-gallery#451] opened 2019-10-29 07:25 UTC
When I render multiple Galleries and press arrow keys on keyboard then both galleries are affected .
How to fix it?
https://codesandbox.io/s/adoring-hellman-7bsls

This is problematic in my case I have several modal dialog sometimes on top of each other, and each of them have a separate Gallery, then when I click an arrow key on the top modal box and close it, it affects also the Gallery in modal below it and images are shifted.

**Comment by xiaolin** [comment] 2019-10-29 19:11
This is a bug, and is being worked on with #446. I'll also try to apply a fix next week if #446 is not finished.

**Comment by natterstefan** [comment] 2019-12-09 08:11
Hi @tsotneguti (//cc @xiaolin),

I was working on it, but other tasks interrupted me. Hopefully in the next few days, I get some time to work on it again.

**Comment by xiaolin** [comment] 2019-12-22 04:33
After putting some more thought into this, its not a bug. 
You should only be rendering the gallery that is active and not multiple at the same time.
If you must render multiple galleries at the same time like in the `codesandbox` above then you need to identify the "active" gallery and disable the arrow keys on the other render galleries using `disableArrowKeys`

**Comment by natterstefan** [comment] 2019-12-30 17:42
Hi @xiaolin (//cc @tsotneguti).

> You should only be rendering the gallery that is active and not multiple at the same time.

Sorry and with all respect, but I disagree with you. There are some reasons I can think of, why one renders multiple galleries at the same time.

For example: a publisher renders it's article page on the server already for better SEO, including _all_ galleries of the article. This allows the publisher to have the content indexed by the search engine, instead of rendering it afterwards in the client only.

At least that's what we do and that's where we discovered the issue (which in our opinion is indeed a bug).

> you need to identify the "active" gallery and disable the arrow keys on the other render galleries using disableArrowKeys

This is something the gallery can (and should IMHO) handle without lifting the heavy weight to users of the code easily. Actually it's quit simple and I'll pick the major changes from my https://github.com/xiaolin/react-image-gallery/pull/446 in another PR.

**Comment by natterstefan** [comment] 2019-12-30 19:09
Hi @xiaolin (//cc @tsotneguti),

I opened a PR here: https://github.com/xiaolin/react-image-gallery/pull/464.

**Comment by xiaolin** [comment] 2020-01-05 05:30
Closing this thread and leaving all future comments to #464

**Closed by xiaolin** 2020-01-05 05:30 UTC
