### ISSUE TITLE
Getting Errors on attempting to Install 

### ISSUE THREAD

**Issue by ErnestAbbott** [xiaolin/react-image-gallery#571] opened 2021-02-10 04:01 UTC
This is just what I'm looking for. However, seeing I get an error on attempting to installing the package, I can't progress. I have only a few weeks at ReactJS so very limited knowledge/understanding. 

I tried --force but that didn't work either. 

Here is installation/error log
  
![ErrorInstalling](https://user-images.githubusercontent.com/17916226/107462608-6f82aa00-6b97-11eb-86b6-7b7585125bb8.png)

**Comment by xiaolin** [comment] 2021-02-20 08:11
Try removing node_modules and trying again. Are you able to install other packages?

**Comment by mohammadalijf** [comment] 2021-02-21 16:56
Same here...
Get same error from `npm install`
At first I thought maybe peerDependencies is set to react 16 only but after checking package.json I realized it is not the problem.
I also tried `npm cache clean --force` to purge previous caches but still no luck.

Maybe moving react to devDependencies in react-image-gallery would solve the problem. or yet better solution would be using `"react": ">= 16.0.0"` instead of `"react": "^16.0.0 || ^17.0.0"`

**Comment by mohammadalijf** [comment] 2021-02-21 17:19
By the way yarn was happy to successfully install project dependencies with this warning:
`warning "react-image-gallery > react-swipeable@5.5.1" has incorrect peer dependency "react@^16.0.0-0".`

**Comment by TheLordA** [comment] 2021-02-22 11:01
i think the problem is that the 1.0.8 release support just react@16 , but the latest commited code added the support for the react@17 . so maybe push a new release may solve the issue.
Correct me if i'am wrong.

**Comment by xiaolin** [comment] 2021-02-22 19:11
Will take a look and fix. Thanks for reporting!

**Comment by xiaolin** [comment] 2021-02-23 01:01
@TheLordA I've not released the latest code so as far as 1.0.8 is concerned it does not see the updated package.json. Take a look at your `node_module/react-image-gallery/package.json` I'm unable to replicate this and will be releasing 1.0.9 with the updated `peerDependencies`.

I tested locally by running `npm install react-image-gallery` on 
node v8.10.0
npm 5.6.0

**Comment by rodneytamblyn** [comment] 2021-02-24 00:25
Build failed here too (OSX 10.15.5)

```
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (.../react-image-gallery/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.5.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/15.9.0/bin/node" ".../react-image-gallery/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /react-image-gallery/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

**Comment by xiaolin** [comment] 2021-03-02 01:47
Updated package to use yarn and removed package-lock.json. Please try again by clearing node modules and installing via yarn.

```bash
cd react-image-gallery
rm -rf node_module
yarn install
```

**Comment by xiaolin** [comment] 2021-03-05 04:01
closing now, feel free to reopen if yarn install is not working with node version < 12

**Closed by xiaolin** 2021-03-05 04:01 UTC
Labels: chore, merged

**Comment by matheus-garcia** [comment] 2021-04-28 05:46
Not sure why, trying to install it with npm didn't for me either, even deleting node_modules folder, had to use yarn instead.

**Comment by Y0ngg4n** [comment] 2021-05-18 18:50
Having same issue again:
```
	Step 4/14 : RUN npm cache verify && npm cache clean --force && npm install -g npm && npm install
100s
113	 ---> Running in 86db78cbc02c
105s
114	Cache verified and compressed (~/.npm/_cacache):
111s
115	Content verified: 0 (0 bytes)
111s
116	Index entries: 0
111s
117	Finished in 0.014s
111s
118	npm WARN using --force I sure hope you know what you are doing.
111s
119	/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
124s
120	/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
124s
121	+ npm@7.13.0
124s
122	added 59 packages from 24 contributors, removed 240 packages and updated 195 packages in 12.018s
124s
123	npm ERR! code ERESOLVE
128s
124	npm ERR! ERESOLVE unable to resolve dependency tree
128s
125	npm ERR! 
128s
126	npm ERR! Found: react@17.0.1
128s
127	npm ERR! node_modules/react
128s
128	npm ERR!   react@"^17.0.1" from the root project
128s
129	npm ERR!   peer react@"^16.0.0 || ^17.0.0" from react-image-gallery@1.0.9
129s
130	npm ERR!   node_modules/react-image-gallery
129s
131	npm ERR!     react-image-gallery@"^1.0.9" from the root project
129s
132	npm ERR!   3 more (react-scripts, react-sortable-hoc, use-count-up)
129s
133	npm ERR! 
129s
134	npm ERR! Could not resolve dependency:
129s
135	npm ERR! peer react@"^16.0.0-0" from react-swipeable@5.5.1
129s
136	npm ERR! node_modules/react-image-gallery/node_modules/react-swipeable
129s
137	npm ERR!   react-swipeable@"^5.2.0" from react-image-gallery@1.0.9
129s
138	npm ERR!   node_modules/react-image-gallery
129s
139	npm ERR!     react-image-gallery@"^1.0.9" from the root project
129s
140	npm ERR! 
129s
141	npm ERR! Fix the upstream dependency conflict, or retry
129s
142	npm ERR! this command with --force, or --legacy-peer-deps
129s
143	npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
129s
144	npm ERR! 
129s
145	npm ERR! See /root/.npm/eresolve-report.txt for a full report.
130s
146	
130s
147	npm ERR! A complete log of this run can be found in:
130s
148	npm ERR!     /root/.npm/_logs/2021-05-18T18_44_09_377Z-debug.log
130s
149	The command '/bin/sh -c npm cache verify && npm cache clean --force && npm install -g npm && npm install' returned a non-zero code: 1
202s
150	time="2021-05-18T18:45:23Z" level=fatal msg="exit status 1"
202s
151	[0m	202s

```

**Comment by xiaolin** [comment] 2021-05-18 18:58
@Y0ngg4n please use `yarn` to install 

@matheus-garcia At the moment only node <= 11 will work due to the current GULP build. Until the build script is upgraded, it currently does not support node > 11.

Planning to fix it via https://github.com/xiaolin/react-image-gallery/issues/586

**Comment by Y0ngg4n** [comment] 2021-05-18 19:25
@xiaolin Thanks for your quick response. Thought it was my fault by using a too old node container version (Because of this i deleted my post). 
I will try it with `yarn` :)

**Comment by Y0ngg4n** [comment] 2021-05-18 22:21
@xiaolin worked thank you :)
