### ISSUE TITLE
thumbnail start to go offscreen

### ISSUE THREAD

**Issue by ramneekhanda** [xiaolin/react-image-gallery#471] opened 2020-01-12 11:53 UTC
In my case i have images with varying heights & thumbnails on the left and i notice that the thumbnails do not scroll exactly one image so slowly they start to go offscreen - this May also be due to the fact that I do load images in pages.

Let me know if more data is required.

**Comment by xiaolin** [comment] 2020-01-13 03:57
Hmm, I  might have seen this before. Can you provide me a set of `items` so I can replicate this?

**Comment by ramneekhanda** [comment] 2020-01-14 13:54
will do by this weekend - a bit busy with stuff today

**Comment by xiaolin** [comment] 2020-05-08 01:58
Closing as this is quite old. Please feel free to reopen with reproducible steps.

**Closed by xiaolin** 2020-05-08 01:58 UTC
Labels: need-investigation

**Comment by nativ3-io** [comment] 2020-05-21 22:24
I had this same issue but after reading this thread, i got it working. Simply because i added flex on the thumbnail main wrapper, to make it centered. adding flex align center will missed the calculations. So i removed the flex and it's working again.
