### ISSUE TITLE
Fullscreen thumbs go offscreen

### ISSUE THREAD

**Issue by AverTry** [xiaolin/react-image-gallery#679] opened 2022-07-04 09:43 UTC
**Describe the bug**

Using your example:

```
import ImageGallery from 'react-image-gallery';

const images = [
  {
    original: 'https://picsum.photos/id/1018/1000/600/',
    thumbnail: 'https://picsum.photos/id/1018/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1015/1000/600/',
    thumbnail: 'https://picsum.photos/id/1015/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1019/1000/600/',
    thumbnail: 'https://picsum.photos/id/1019/250/150/',
  },
];

class MyGallery extends React.Component {
  render() {
    return <ImageGallery items={images} />;
  }
}
```
In normal view click on third image, now go Fullscreen, and this happens:

![image](https://user-images.githubusercontent.com/72357571/177127588-2ab8015e-b9dc-43a9-a51c-52c68ed9d470.png)

**Image Gallery Version**
What version of `react-image-gallery` are you using?

"react-image-gallery": "^1.2.8"

**To Reproduce**
See above:

**Expected behavior**
Stay Centered

**Screenshots**

See Above:

**Desktop (please complete the following information):**
 
Windows 11 Pro: Chrome Engine based browsers - Brave, Opera, Edge
  "dependencies": {
    "next": "12.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-image-gallery": "^1.2.8"
  },
  "devDependencies": {
    "eslint": "8.18.0",
    "eslint-config-next": "12.2.0",
    "gray-matter": "^4.0.3",
    "next-mdx-remote": "^4.0.3",
    "remark-gfm": "^3.0.1"
  }

**Additional context**

My quick hack fix that will most likely fail on a large gallery is css to force it to be centered.

/* Bug fix hack, fullscreen disapearing nav */
.image-gallery-thumbnails-container {
  transform: translate3d(0px, 0px, 0px) !important;
}

**Comment by xiaolin** [comment] 2022-07-28 17:10
Do you see the same issue when visiting the demo link? http://linxtion.com/demo/react-image-gallery

**Comment by alexdevmotion** [comment] 2022-08-17 06:00
I am running into the same issue with vertical thumbnails - it seems to be something related to how `scrollHeight` is computed internally.
![image](https://user-images.githubusercontent.com/7261890/185045245-2cab8444-d425-4edf-8475-2c14564c4566.png)

What is funny is that if I change the vertical size of the browser window, it suddenly starts to work and it only goes back to the bug if I refresh the page.

In `ImageGallery.js` there's this logic:
```
      if (this.isThumbnailVertical()) {
        if (thumbsElement.scrollHeight <= thumbnailsWrapperHeight) {
          return 0;
        }
...
```
Seems like one of those is not correctly computed (it's not returning 0) before the browser window height is being changed, for some weird reason.

Will try to create a codepen replicating the issue.

**Comment by xiaolin** [comment] 2022-08-18 00:45
Looks like this is a duplicate of #674 and happening for react >= 18 when a new render was introduced.

**Comment by xiaolin** [comment] 2022-08-18 00:47
Duplicate of #674

**Comment by xiaolin** [comment] 2022-08-18 00:48
Closing in favor of #674

**Closed by xiaolin** 2022-08-18 00:48 UTC
Labels: duplicate
