### ISSUE TITLE
Thumbnail wrapper height not set properly if thumbnails load slowly

### ISSUE THREAD

**Issue by mattwexa** [xiaolin/react-image-gallery#284] opened 2018-05-22 15:10 UTC
Hi there,

this component is great, except for a small bug I noticed. I'm using the images themselves as thumbnails as a starting point, and sometimes this results in the `image-gallery-thumbnails-wrapper` div having a height that is too small (like 26px).

This can be reproduced by having thumbnails that are slow to load (for instance setting the network connection speed to Slow 3G in Chrome). I believe this may be due to the timeout in handleResize being too small. I wonder : why do we need to set the height of that `div`? If we need it, this could be solved by using the `onImageLoad` to track when all thumbnail images have been loaded.

What do you think?

Thanks!

**Comment by xiaolin** [comment] 2018-05-24 02:44
Duplicate of #266

**Closed by xiaolin** 2018-05-24 02:44 UTC

**Comment by mattwexa** [comment] 2018-05-24 07:06
Oops sorry 🙁 I did search initially for issues before reporting this, but probably not with the right keywords. I changed the title several times, and now I see it's almost identical to the original issue 🙂

**Comment by xiaolin** [comment] 2018-05-24 14:07
Haha, I actually changed the title of the original issue because it was very confusing. I ended up copying your title and adjusting it.
