### ISSUE TITLE
Use component in full screen mode only.

### ISSUE THREAD

**Issue by DannyNobul** [xiaolin/react-image-gallery#487] opened 2020-02-24 13:50 UTC
First off, thanks for all the hard work you did on making this library.

I was just wondering if you can add a property to use the gallery in full screen mode only. At the moment I am using state, refs, and the fullScreen()/exitFullScreen() functions to toggle it. However, I am getting some weird issues where the functions don't fire and I am stuck with the minimized version.

Thanks again.

**Comment by xiaolin** [comment] 2020-03-02 05:40
There are currently two fullscreen modes. One for the desktop ([Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)) and one for mobile ("fake" fullscreen using CSS). I don't believe you can force a fullscreen without a way to toggle off for a desktop user because that would take over their screen.

The "fake" fullscreen however can be done via CSS on your end.

**Comment by xiaolin** [comment] 2020-03-02 06:03
This is actually a duplicate of #474. Will close in favor of that thread.

**Closed by xiaolin** 2020-03-02 06:03 UTC
Labels: question, uncertain
