### ISSUE TITLE
Safari not smooth auto playing images behavior

### ISSUE THREAD

**Issue by anthonyvialleton** [xiaolin/react-image-gallery#333] opened 2018-09-28 16:28 UTC
On **Safari 12.0** when enabling auto play, make it infinite, removing thumbnails and with this interval I could reproduce the bug we have in our project as follow : 

![ezgif com-optimize](https://user-images.githubusercontent.com/7242728/46220928-ef53a500-c34b-11e8-8a87-2064918e2dd4.gif)

As you can see, it's not a framerate GIF issue there but images are not smoothly transitioned when autoplayed. A transparent image is actually shown instead of the smooth 'image pushing' animation.
  
Here is our complete configuration : 

` <ImageGallery
      autoPlay
      infinite
      items={slides}
      lazyLoad
      showThumbnails={false}
      showFullscreenButton={false}
      showPlayButton={false}
      showBullets
      slideDuration={250}
      slideInterval={4000}
      renderLeftNav={renderLeftNav}
      renderRightNav={renderRightNav}
    />`

**Comment by xiaolin** [comment] 2018-10-29 15:27
Seems to be isolated to safari. I wonder why...

**Comment by chrkaatz** [comment] 2018-12-04 12:01
I could reproduce this by setting showThumbnails to false on safari, if I enable them, it runs smoothly

**Comment by xiaolin** [comment] 2019-05-06 23:48
How to reproduce:

Safari browser
```
autoPlay={true}
showThumbnails={false}
```

**Comment by xiaolin** [comment] 2019-07-05 03:31
This looks to be fixed by safari and is no longer reproducible. Feel free to reopen if you can reproduce on latest safari.

**Closed by xiaolin** 2019-07-05 03:31 UTC
Labels: bug, help wanted
