### ISSUE TITLE
Screen readers - Constantly reading alt text of slides while not focussed

### ISSUE THREAD

**Issue by kylane** [xiaolin/react-image-gallery#547] opened 2020-09-29 00:57 UTC
Hi guys,

Huge fan of the component, but having some screen reader issues (MacOs and NVDA) where the slides alt text is being read on every change of slide, even when not focussed - so its constantly reading out the slides when trying to navigate around other items.

**Comment by jw-miaem** [comment] 2020-10-02 15:43
@kylane I think this is expected behaviour with aria polite

**Comment by xiaolin** [comment] 2020-10-05 03:38
I believe that is intended with aria-polite as @jw-miaem mentioned. I'm open to other suggestions if that is not expected.

**Comment by jw-miaem** [comment] 2020-10-16 14:45
@kylane @xiaolin after testing I found this was an issue - I forked the gallery and moved aria live to the main image carousel and set all images to aria-hidden true unless they have center class applied

**Comment by kylane** [comment] 2020-10-18 23:36
> @kylane @xiaolin after testing I found this was an issue - I forked the gallery and moved aria live to the main image carousel and set all images to aria-hidden true unless they have center class applied

I did similar, plus a few other small things as well.

**Comment by xiaolin** [comment] 2020-11-24 08:08
closing this, feel free to open an issue/pr of fix

**Closed by xiaolin** 2020-11-24 08:08 UTC
Labels: question
