### ISSUE TITLE
All images are retrieved instead of one. 

### ISSUE THREAD

**Issue by pwujczyk** [xiaolin/react-image-gallery#580] opened 2021-04-25 21:18 UTC
Hi!

I am using your cool gallery and I am struggling with calls to server. Probably I am doing something wrong, but I cannot find it. Could you look at it? 

I created my component and added simple code

```
function Gallery() {

    const [serverImages, setserverImages] = useState([]);

    const getLinks = () => {

        let x= window.innerHeight;
        console.log(x);
        console.log("get from endpoint");
        fetch(`https://localhost:5001/api/Images/List?height=`+x, {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' }
        })
            .then(response => response.json())
            .then(result => setserverImages(result));
    }

    const handleClick=function(){
        debugger;
        getLinks();
    }

    return (
        <div>
            <button onClick={handleClick}>zrob</button>
            <ImageGallery items={serverImages} />
        </div>

    )
}

export default Gallery;
```

Unfortunatelly after each click on the button next, all images are received from server. 
So I have a gallery loaded. All small pictures below, one big picture in the middle of the screen.  
![Gallery1](https://user-images.githubusercontent.com/20401771/116009886-2e3d5a80-a61c-11eb-912a-f94e15375392.png)

My network is empty
![Gallery2](https://user-images.githubusercontent.com/20401771/116009910-49a86580-a61c-11eb-9df1-fbddfd975c5f.png)

After clicking button next calls to all images is made. And all images are retrieved, each time I am clicking next button. 

![Gallery3](https://user-images.githubusercontent.com/20401771/116009939-6c3a7e80-a61c-11eb-92d5-ce8a6d86bbdb.png)

**Comment by xiaolin** [comment] 2021-04-26 17:46
Looks like somewhere in your code you're re-rendering your functional component `< Gallery />` again. I would take the server call for images out of your component so that it is only called once.

**Comment by pwujczyk** [comment] 2021-04-26 20:03
@xiaolin thank you for answering! 

the call for the images is done directly by the ImageGallery component. My custom call to server is done only once and it is used to provide items property to ImageGallery. 

```
import './App.css';
import Gallery from './Components/Gallery'


function App() {
  return (
    <div className="App">
      <Gallery></Gallery>
    </div>
  );
}

export default App;

```

**Comment by xiaolin** [comment] 2021-05-06 20:57
Instead of using server images can you use a list of static images and try to reproduce? It may be something with how the images are served.

Try doing a simple render and see if you can replicate

```jsx
import ImageGallery from 'react-image-gallery';

const images = [
  {
    original: 'https://picsum.photos/id/1018/1000/600/',
    thumbnail: 'https://picsum.photos/id/1018/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1015/1000/600/',
    thumbnail: 'https://picsum.photos/id/1015/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1019/1000/600/',
    thumbnail: 'https://picsum.photos/id/1019/250/150/',
  },
];

class MyGallery extends React.Component {
  render() {
    return <ImageGallery items={images} />;
  }
}
```

**Comment by pwujczyk** [comment] 2021-05-07 11:51
Yes, when I use static list it is working without any issues. I don't know why it is not working with list provided from server, I also tried to change the urls to have it in similar format without luck. 

I will try to dig into it next week.

**Comment by ryanhugh** [comment] 2021-05-07 21:18
@pwujczyk  Try unchecking the "Disable Cache" in your chrome dev tools and see if that fixes the issue.

**Comment by xiaolin** [comment] 2021-05-18 05:00
closing, feel free to reopen if you find issues.

**Closed by xiaolin** 2021-05-18 05:00 UTC
Labels: cant-replicate, question
