### ISSUE TITLE
Swiping through images in a gallery getting an error

### ISSUE THREAD

**Issue by hchoriq** [xiaolin/react-image-gallery#321] opened 2018-09-10 05:26 UTC
Sorry - maybe all these errors are just me doing something wrong. But I set up a gallery and as I'm scrolling through the images, I get this error:

![image](https://user-images.githubusercontent.com/15879364/45277884-4538d980-b47f-11e8-95f4-4c384e908818.png)

![image](https://user-images.githubusercontent.com/15879364/45277898-5aae0380-b47f-11e8-991a-ba1246421bb2.png)

That's react-swipeable, not react-image-gallery, right? I just want to make sure I'm setting this up right before I ask a question elsewhere.

**Comment by xiaolin** [comment] 2018-09-12 21:54
Do you get the same error on the example page http://linxtion.com/demo/react-image-gallery? If so how do you reproduce this.

**Comment by ekrokowski** [comment] 2019-02-05 12:10
@xiaolin Yes, I get the same error on the example page. But i guess that needs to be fixed in `react-swipeable`. 
The event should only be prevented if `e.cancelable` is true.

Reproduce:
1. Chrome Version: 71.0.3578.98 
2. Responsive/Mobile emulation on
3. Swipe on image to next slide
4. The error triggers several times

**Comment by hartzis** [comment] 2019-03-14 03:16
@xiaolin as the `react-swipeable` maintainer i'd like to carve out some time this week or next to see if I can get a PR to `react-image-gallery` to:
- update `react-swipeable` to v5
- include a fix for the "errors"
  - by only calling `preventDefault` when necassary
    - either within `react-image-gallery` using the `event` itself provided by `react-swipeable`
    - or the "error" might get fixed when fixing this issue: https://github.com/dogfessional/react-swipeable/issues/127

**A note** these errors are more like warnings, since `Calling preventDefault() for a non-cancelable event has no effect`, [MDN web docs - preventDefault#Notes](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault#Notes)

**Comment by xiaolin** [comment] 2019-03-14 14:15
@hartzis That would be amazing!

If you're unable to get to it let me know and I'll try to allocate some time to update it.

**Comment by hartzis** [comment] 2019-03-17 21:44
I think I may have grossly underestimated the complexity of this package and the time required. Just spent an hour and still having a hard time fully grasping `react-swipeable`'s integration.

I will probably be unable to commit the time required to address this issue.

#### Thoughts:
- this warning is ultimately a deeper issue related to how `react` attaches its `touchstart`/`touchmove` event listeners to the `document` and not the containers themselves
  - https://github.com/facebook/react/issues/2043
- **recommend** removing the dependency on `react-swipeable`
  - this will allow you to attach the touch event listeners directly to the gallery's container.
    - example: https://github.com/casesandberg/react-color/pull/594
    - if `react-image-gallery` just attached the `touchstart` and `touchmove` listeners to the galleries container, then this should allow the gallery the ability to call `e.preventDefault()` more appropriately
  - can easily copy whatever code from `react-swipeable` that is needed

**Comment by xiaolin** [comment] 2019-03-18 22:29
Thanks for the update @hartzis, I have been wanting to remove the dependency for a bit now and this might be a good opportunity for me to do so. I'll take a look at removing the dependency or updating it whichever is best.

**Closed** 2019-05-27 17:59 UTC
Labels: bug, help wanted

**Comment by HenrikeStahlhut** [comment] 2024-03-01 13:58
Are there any updates regarding this problem? Because I've ran into the same issue now. When swiping on mobile in fullscreen, I get a ton of `Unable to preventDefault inside passive event listener invocation` erros at every swipe. 

I haven't found a solution jet and I am also not sure if this is due to a problem with `react-swipeable` / `react-image-library` or my fault. 

Any help would be greatly appreciated!
