### ISSUE TITLE
onTouchStart results in unexpected behavior

### ISSUE THREAD

**Issue by gaborluk** [xiaolin/react-image-gallery#58] opened 2016-05-18 16:45 UTC
With [this line](https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L459) in place, merely scrolling past the image gallery with the scrolling finger touching the area of the gallery will result in the triggering of the custom `onClick` method, which, in turn, might do things like opening a larger image on a modal; a very unexpected behavior and frustrating user experience.

The `onClick` should trigger just fine on tap events on touch devices, there is no need to specify a separate `onTouchStart` if the goal is simply to make sure that the custom `onClick` method works on these devices. Is there any other reason for having included this line, or is it safe to remove it?

**Comment by xiaolin** [comment] 2016-05-18 16:59
I see what you mean, but I'm not 100% sure its safe to remove. I think it was added from a PR.

**Comment by xiaolin** [comment] 2016-05-18 17:01
Its probably safe to remove.

**Comment by gaborluk** [comment] 2016-05-18 17:11
Cool, let me know your thoughts regarding https://github.com/xiaolin/react-image-gallery/issues/57, and I'll remove this line in the same PR.

**Comment by gaborluk** [comment] 2016-05-18 22:24
After removing `onTouchStart`, what I'm noticing is that continuously tapping on the image will only get the `onClick` handler to fire every few seconds. I'm guessing this has something to do with the `throttle` function, but that part is quite chaotic and I'm not sure if that's the culprit at all. Do you have any ideas of what might be causing this, @xiaolin?

**Comment by gaborluk** [comment] 2016-05-18 22:29
Indeed, if I remove `onTouchEnd` as well, `onClick` works consistently and as expected. What purpose is that guy meant to serve?

**Comment by xiaolin** [comment] 2016-05-18 22:29
throttle is only applied to the `_slideLeft` and `_slideRight` so it shouldn't be that.

So I think the problem is once you remove `onTouchStart`, the `onClick` function is wraped by `_wrapClick`, that function does some stuff to prevent ghost clicks, and thats probably why its getting delayed, and not working correctly.

```
          onClick={this._wrapClick(this.props.onClick)}
          onTouchStart={this.props.onClick}
```

**Comment by xiaolin** [comment] 2016-05-18 22:31
If I remember correctly `_touchEnd` and `touchStart` prevents ghostclicks #37

**Comment by gaborluk** [comment] 2016-05-18 22:43
Unfortunately, this changeset apparently doesn't work as intended, I'm not sure if the whole ghost click issue is worth dealing with if the solution involves relying on `touchstart` to provide `click` functionality, which results in unexpected actions taking place when scrolling on touch devices. To be honest, I don't have a complete understanding of what issue https://github.com/xiaolin/react-image-gallery/pull/37 solves, so I'm curious about your input.

**Comment by xiaolin** [comment] 2016-05-18 23:51
I will take a look into it.

**Comment by xiaolin** [comment] 2016-05-19 00:33
@gaborluk I've pushed a recent commit that should fix the onclick events firing on mobile swipes. Let me know if that works well.

**Comment by gaborluk** [comment] 2016-05-19 10:47
Thanks, @xiaolin, it's a much better situation now as there is nothing firing when you scroll with your finger on the main image, however, other elements of the gallery (thumbnails, bullets, navigation) still react to `touchstart`. Which, of course, is by far not as big an issue since all these do is trigger a slide, but if it doesn't break anything else then I would recommend fixing these, too, because ultimately the sliding is unexpected.

**Comment by xiaolin** [comment] 2016-05-20 14:31
I purposely left the `touchStart` on the thumbnails, bullets, and navigation. Having them as onClick results in a delay on mobile devices. are you having issues swiping on those controls?

**Comment by gaborluk** [comment] 2016-05-20 14:58
No, scrolling happens properly regardless of being initiated on one of these elements or not, I was just commenting on the control handlers firing as a side-effect of scrolling, and not as an intended action in these cases. As I've said, this is a much less serious issue than the custom `onClick` handler firing on the main image's `touchstart`, ultimately you're juggling two similarly frustrating mobile UX concerns, of which keeping one or the other will have to be a fairly subjective decision, so it's really up to you. I'm already happy with the original issue being taken care of.

**Comment by xiaolin** [comment] 2016-05-20 15:02
Ah, okay. I'm going to close this issue for now. Thanks!

**Closed by xiaolin** 2016-05-20 15:02 UTC
